$axure.loadCurrentPage({
  "url":"confirmation.html",
  "generationDate":new Date(1397114343576.63),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"e2f0faefe0004ae1a9da597af00d9240",
    "type":"Axure:Page",
    "name":"confirmation",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"6547ec94518a409fa3734dc667c90966",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":320,
              "height":1400}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"38de52a9d8834d7caaf0ffb9fd3e5f29",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":320,
                  "height":1400}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/confirmation/u0.jpg"}}]}},
  "masters":{
},
  "objectPaths":{
    "6547ec94518a409fa3734dc667c90966":{
      "scriptId":"u0"},
    "38de52a9d8834d7caaf0ffb9fd3e5f29":{
      "scriptId":"u1"}}});