$axure.loadCurrentPage({
  "url":"searchresult_orchard.html",
  "generationDate":new Date(1397187883846.68),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"12b47a02b7bc419f8a26dff3e96b0517",
    "type":"Axure:Page",
    "name":"SearchResult_orchard",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"910221c68b32423da442fa0ed427cf08",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":320,
              "height":1400}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"34849267d63c4c32ab545c67e8b92641",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":320,
                  "height":1400}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/searchresult_orchard/u0.jpg"}},
{
          "id":"d0c32ef34b2448369fecd9b349b8270e",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "size":{
              "width":60,
              "height":50}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Back in Current Window",
                      "target":{
                        "targetType":"backUrl",
                        "includeVariables":false},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"5600f79308a14e568936dda823ec2fa3",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":90},
            "size":{
              "width":320,
              "height":110}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open confirmation in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"confirmation.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"dbd558b6f5104698ae596a15230d48a8",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":210},
            "size":{
              "width":320,
              "height":110}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open confirmation in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"confirmation.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"c771f859f0c246bca0ae0d09e1186e36",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":330},
            "size":{
              "width":320,
              "height":110}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open confirmation in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"confirmation.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"001f1ae718d549bfbdd2e448d8b66bf9",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":450},
            "size":{
              "width":320,
              "height":120}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open confirmation in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"confirmation.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"ba44dfc2a1f64867b06bd925fef55ee3",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":580},
            "size":{
              "width":320,
              "height":110}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open confirmation in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"confirmation.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"9ae6f8d708d44e44aef25c88f3873047",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":700},
            "size":{
              "width":320,
              "height":110}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open confirmation in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"confirmation.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"26d0cb34a46c4367b465ce06d2a5a9ae",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":820},
            "size":{
              "width":320,
              "height":110}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open confirmation in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"confirmation.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"b01395cd073b4173b5de7c51846d2b4d",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":940},
            "size":{
              "width":320,
              "height":110}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open confirmation in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"confirmation.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"1ecc0ffccd594d85884eb4f9700c75d3",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":1060},
            "size":{
              "width":320,
              "height":110}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open confirmation in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"confirmation.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"e9e06e5fd2a141e1afb96bf067cbc1ae",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":1184},
            "size":{
              "width":320,
              "height":110}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open confirmation in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"confirmation.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true}]}},
  "masters":{
},
  "objectPaths":{
    "910221c68b32423da442fa0ed427cf08":{
      "scriptId":"u0"},
    "34849267d63c4c32ab545c67e8b92641":{
      "scriptId":"u1"},
    "d0c32ef34b2448369fecd9b349b8270e":{
      "scriptId":"u2"},
    "5600f79308a14e568936dda823ec2fa3":{
      "scriptId":"u3"},
    "dbd558b6f5104698ae596a15230d48a8":{
      "scriptId":"u4"},
    "c771f859f0c246bca0ae0d09e1186e36":{
      "scriptId":"u5"},
    "001f1ae718d549bfbdd2e448d8b66bf9":{
      "scriptId":"u6"},
    "ba44dfc2a1f64867b06bd925fef55ee3":{
      "scriptId":"u7"},
    "9ae6f8d708d44e44aef25c88f3873047":{
      "scriptId":"u8"},
    "26d0cb34a46c4367b465ce06d2a5a9ae":{
      "scriptId":"u9"},
    "b01395cd073b4173b5de7c51846d2b4d":{
      "scriptId":"u10"},
    "1ecc0ffccd594d85884eb4f9700c75d3":{
      "scriptId":"u11"},
    "e9e06e5fd2a141e1afb96bf067cbc1ae":{
      "scriptId":"u12"}}});