$axure.loadCurrentPage({
  "url":"searchresult_orchard.html",
  "generationDate":new Date(1397120261300.93),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"12b47a02b7bc419f8a26dff3e96b0517",
    "type":"Axure:Page",
    "name":"SearchResult_orchard",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"910221c68b32423da442fa0ed427cf08",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":320,
              "height":1400}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"34849267d63c4c32ab545c67e8b92641",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":320,
                  "height":1400}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/searchresult_orchard/u0.jpg"}}]}},
  "masters":{
},
  "objectPaths":{
    "910221c68b32423da442fa0ed427cf08":{
      "scriptId":"u0"},
    "34849267d63c4c32ab545c67e8b92641":{
      "scriptId":"u1"}}});