$axure.loadCurrentPage({
  "url":"searchresult_bugis.html",
  "generationDate":new Date(1397187883730.37),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"4436b1cfd0434572b2498d192e3c2f45",
    "type":"Axure:Page",
    "name":"SearchResult_bugis",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"c8807a343d6f4b33981a278c13317356",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":320,
              "height":1398}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"47b007b3e25b4d0fb28ee5b773c785da",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":320,
                  "height":1398}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/searchresult_bugis/u0.jpg"}},
{
          "id":"4f5beba6010d4e788256789507d9bb49",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":90},
            "size":{
              "width":320,
              "height":110}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open confirmation in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"confirmation.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"18516b4ca5e94fd7a3e0a298e999ebc1",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":210},
            "size":{
              "width":320,
              "height":110}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open confirmation in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"confirmation.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"c3a9b8c556d64078b7ecbb4c4d3cb600",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":330},
            "size":{
              "width":320,
              "height":110}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open confirmation in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"confirmation.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"bd524299c30640d29a02507b233e17f5",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":455},
            "size":{
              "width":320,
              "height":110}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open confirmation in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"confirmation.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"f74afe478d4243659664bed2bc94c72f",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":575},
            "size":{
              "width":320,
              "height":110}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open confirmation in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"confirmation.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"ccc0557fa197417b84c0850049aac793",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":704},
            "size":{
              "width":320,
              "height":110}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open confirmation in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"confirmation.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"0f68694baa1940bcab254bc5233a5bb7",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":-1,
              "y":822},
            "size":{
              "width":320,
              "height":110}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open confirmation in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"confirmation.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"52c10f30e1904f2592cb0a136820fee0",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":938},
            "size":{
              "width":320,
              "height":110}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open confirmation in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"confirmation.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"970c5d3989e74352ab5e5f2a528203e0",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":1058},
            "size":{
              "width":320,
              "height":110}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open confirmation in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"confirmation.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"a9b01c041c194308903fba9dc2c77ea2",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":1183},
            "size":{
              "width":320,
              "height":110}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open confirmation in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"confirmation.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"53c39455bf5c4aad88b0ec5386aff474",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "size":{
              "width":60,
              "height":50}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Back in Current Window",
                      "target":{
                        "targetType":"backUrl",
                        "includeVariables":false},
                      "linkType":"current"}]}]}},
          "tabbable":true}]}},
  "masters":{
},
  "objectPaths":{
    "c8807a343d6f4b33981a278c13317356":{
      "scriptId":"u0"},
    "47b007b3e25b4d0fb28ee5b773c785da":{
      "scriptId":"u1"},
    "4f5beba6010d4e788256789507d9bb49":{
      "scriptId":"u2"},
    "18516b4ca5e94fd7a3e0a298e999ebc1":{
      "scriptId":"u3"},
    "c3a9b8c556d64078b7ecbb4c4d3cb600":{
      "scriptId":"u4"},
    "bd524299c30640d29a02507b233e17f5":{
      "scriptId":"u5"},
    "f74afe478d4243659664bed2bc94c72f":{
      "scriptId":"u6"},
    "ccc0557fa197417b84c0850049aac793":{
      "scriptId":"u7"},
    "0f68694baa1940bcab254bc5233a5bb7":{
      "scriptId":"u8"},
    "52c10f30e1904f2592cb0a136820fee0":{
      "scriptId":"u9"},
    "970c5d3989e74352ab5e5f2a528203e0":{
      "scriptId":"u10"},
    "a9b01c041c194308903fba9dc2c77ea2":{
      "scriptId":"u11"},
    "53c39455bf5c4aad88b0ec5386aff474":{
      "scriptId":"u12"}}});