$axure.loadCurrentPage({
  "url":"searchresult_bugis.html",
  "generationDate":new Date(1397114026230.84),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"4436b1cfd0434572b2498d192e3c2f45",
    "type":"Axure:Page",
    "name":"SearchResult_bugis",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"c8807a343d6f4b33981a278c13317356",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":320,
              "height":1398}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"47b007b3e25b4d0fb28ee5b773c785da",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":320,
                  "height":1398}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/searchresult_bugis/u0.jpg"}}]}},
  "masters":{
},
  "objectPaths":{
    "c8807a343d6f4b33981a278c13317356":{
      "scriptId":"u0"},
    "47b007b3e25b4d0fb28ee5b773c785da":{
      "scriptId":"u1"}}});