$axure.loadCurrentPage({
  "url":"iphone_frame.html",
  "generationDate":new Date(1397187963663.8),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"2319c9ac74df43c9abcfbf8cccec826d",
    "type":"Axure:Page",
    "name":"iphone frame",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"4be172ebd4b2478aab0122565b46e6bc",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":400,
              "height":800}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4852d569dc7a49e5b0b4ed3c74a45f6d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":400,
                  "height":800}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/iphone_frame/u0.png"}},
{
          "id":"7a15bf9ef4ac433a83236dacf9652264",
          "label":"",
          "type":"inlineFrame",
          "styleType":"inlineFrame",
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":137},
            "size":{
              "width":320,
              "height":553}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onMove":{
              "description":"OnMove",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Home in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"home.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "target":{
            "targetType":"page",
            "url":"home.html",
            "includeVariables":true}}]}},
  "masters":{
},
  "objectPaths":{
    "4be172ebd4b2478aab0122565b46e6bc":{
      "scriptId":"u0"},
    "4852d569dc7a49e5b0b4ed3c74a45f6d":{
      "scriptId":"u1"},
    "7a15bf9ef4ac433a83236dacf9652264":{
      "scriptId":"u2"}}});