$axure.loadCurrentPage({
  "url":"homepage-confirmed.html",
  "generationDate":new Date(1397120260360.43),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"226ca7db571b43898e0cd6cfc91f8bbf",
    "type":"Axure:Page",
    "name":"Homepage-confirmed",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"ae73bd429bf64dfa808a505c64bb8904",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":-15},
            "size":{
              "width":320,
              "height":568}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ba059737d875490480e8802db981961e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":-15},
                "size":{
                  "width":320,
                  "height":568}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/homepage-confirmed/u0.png"}},
{
          "id":"e3a0dd8cf7564aa6ac99ea538f13713b",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":160,
              "y":80},
            "size":{
              "width":150,
              "height":30}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Homepage-pending in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"homepage-pending.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"75d10f460dd24738b52d72594017445b",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":503},
            "size":{
              "width":320,
              "height":50}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Create New Event in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"create_new_event.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true}]}},
  "masters":{
},
  "objectPaths":{
    "ae73bd429bf64dfa808a505c64bb8904":{
      "scriptId":"u0"},
    "ba059737d875490480e8802db981961e":{
      "scriptId":"u1"},
    "e3a0dd8cf7564aa6ac99ea538f13713b":{
      "scriptId":"u2"},
    "75d10f460dd24738b52d72594017445b":{
      "scriptId":"u3"}}});