$axure.loadCurrentPage({
  "url":"add_participant.html",
  "generationDate":new Date(1397114025701.29),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"e65ac110b3d341e985007f3ff0ded21b",
    "type":"Axure:Page",
    "name":"Add participant",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"318f6baa86684cb1a952574e287b4180",
          "label":"popup",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":101},
            "size":{
              "width":300,
              "height":279}},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"907af320375149ab946fe3047cd3c162",
              "label":"nothing",
              "type":"Axure:PanelDiagram",
              "objects":[],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}},
{
              "id":"252c1c37608245cfa90fac2e15c46c69",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"66427b11df70457d9e431252aba996b4",
                  "label":"",
                  "parentDynamicPanel":"318f6baa86684cb1a952574e287b4180",
                  "panelIndex":1,
                  "type":"textBox",
                  "styleType":"textBox",
                  "visible":true,
                  "style":{
                    "fontName":"'MyriadPro-Regular', 'Myriad Pro'",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF3DBFD9,
                      "opacity":1},
                    "location":{
                      "x":10,
                      "y":10},
                    "size":{
                      "width":200,
                      "height":25}},
                  "adaptiveStyles":{
}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}}]},
{
          "id":"5f70edcf4312438c810f13d0b8a14b50",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":-15},
            "size":{
              "width":320,
              "height":568}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8636e255f35f4952a993d58e33dc44d6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":-15},
                "size":{
                  "width":320,
                  "height":568}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/add_participant/u2.png"}},
{
          "id":"09e4d65f908143f8954258f6f454b0d3",
          "label":"1",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":false,
          "style":{
            "location":{
              "x":260,
              "y":101},
            "size":{
              "width":30,
              "height":30},
            "visible":false},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4ea18625801f43579ec38bb7c1135c10",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "location":{
                  "x":260,
                  "y":101},
                "size":{
                  "width":30,
                  "height":30},
                "visible":false},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/likes/chinesebtn_u2.png"}},
{
          "id":"e81548a619f84132be1a56ed97e614a8",
          "label":"2",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":false,
          "style":{
            "location":{
              "x":260,
              "y":149},
            "size":{
              "width":30,
              "height":30},
            "visible":false},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"38c16340c4824d2783ab741009c75b98",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "location":{
                  "x":260,
                  "y":149},
                "size":{
                  "width":30,
                  "height":30},
                "visible":false},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/likes/chinesebtn_u2.png"}},
{
          "id":"6634a6c14bdf476daca59c2a3025356b",
          "label":"4",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":false,
          "style":{
            "location":{
              "x":260,
              "y":240},
            "size":{
              "width":30,
              "height":30},
            "visible":false},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6fc5a7a401fd4372a0aa20a0a70148f4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "location":{
                  "x":260,
                  "y":240},
                "size":{
                  "width":30,
                  "height":30},
                "visible":false},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/likes/chinesebtn_u2.png"}},
{
          "id":"3e9740f7b6064e0482fc9e95891ca6e0",
          "label":"5",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":false,
          "style":{
            "location":{
              "x":260,
              "y":290},
            "size":{
              "width":30,
              "height":30},
            "visible":false},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5732f510076a434d93fee9a6f76793e2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "location":{
                  "x":260,
                  "y":290},
                "size":{
                  "width":30,
                  "height":30},
                "visible":false},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/likes/chinesebtn_u2.png"}},
{
          "id":"763386a6a7094fb1b7e701e2d926c5ea",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":101},
            "size":{
              "width":300,
              "height":40}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"Toggle 1",
                      "objectsToFades":[{
                          "objectPath":["09e4d65f908143f8954258f6f454b0d3"],
                          "fadeInfo":{
                            "fadeType":"toggle",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true},
{
          "id":"837b4219f0fa41c1ab10234ac301ebfc",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":141},
            "size":{
              "width":300,
              "height":40}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"Show/Hide Widget",
                      "objectsToFades":[]},
{
                      "action":"fadeWidget",
                      "description":"Toggle 2",
                      "objectsToFades":[{
                          "objectPath":["e81548a619f84132be1a56ed97e614a8"],
                          "fadeInfo":{
                            "fadeType":"toggle",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true},
{
          "id":"73c7f26e05f14a3aa9ae9ee28c2b3871",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":191},
            "size":{
              "width":300,
              "height":40}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"Show 3",
                      "objectsToFades":[{
                          "objectPath":["4aa29a849eea4393b66a6b3edaf47166"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true},
{
          "id":"ac952bcd0e20413882c181c3cfd43f76",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":238},
            "size":{
              "width":300,
              "height":40}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"Toggle 4",
                      "objectsToFades":[{
                          "objectPath":["6634a6c14bdf476daca59c2a3025356b"],
                          "fadeInfo":{
                            "fadeType":"toggle",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true},
{
          "id":"3782ff02c6b84c1bae13fd81f74a1988",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":281},
            "size":{
              "width":300,
              "height":40}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"Toggle 5",
                      "objectsToFades":[{
                          "objectPath":["3e9740f7b6064e0482fc9e95891ca6e0"],
                          "fadeInfo":{
                            "fadeType":"toggle",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true},
{
          "id":"60cb7a8fbbaf496e8f3c2d99b1e00234",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontName":"'MyriadPro-Regular', 'Myriad Pro'",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF3DBFD9,
              "opacity":1},
            "location":{
              "x":35,
              "y":60},
            "size":{
              "width":265,
              "height":25}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onTextChange":{
              "description":"OnTextChange",
              "cases":[{
                  "description":"Case 1<br> (If text on This equals &quot;&quot;)",
                  "isNewIfGroup":false,
                  "condition":{
                    "exprType":"binaryOp",
                    "op":"==",
                    "leftExpr":{
                      "exprType":"fcall",
                      "functionName":"GetWidgetText",
                      "arguments":[{
                          "exprType":"pathLiteral",
                          "isThis":true,
                          "isFocused":false,
                          "isTarget":false}]},
                    "rightExpr":{
                      "exprType":"stringLiteral",
                      "value":"",
                      "stos":[]}},
                  "actions":[{
                      "action":"wait",
                      "description":"Wait 1500 ms",
                      "waitTime":1500},
{
                      "action":"setPanelOrder",
                      "description":"Bring popup to Front ",
                      "panelPaths":[{
                          "panelPath":["318f6baa86684cb1a952574e287b4180"],
                          "setOrderInfo":{
                            "bringToFront":true}}]},
{
                      "action":"setPanelState",
                      "description":"Set popup to State1",
                      "panelsToStates":[{
                          "panelPath":["318f6baa86684cb1a952574e287b4180"],
                          "stateInfo":{
                            "setStateType":"diagram",
                            "stateNumber":2,
                            "stateValue":{
                              "exprType":"stringLiteral",
                              "value":"1",
                              "stos":[]},
                            "loop":false,
                            "showWhenSet":false,
                            "options":{
                              "compress":false}}}]}]}]},
            "onLostFocus":{
              "description":"OnLostFocus",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Reload in Current Window",
                      "target":{
                        "targetType":"reloadPage",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "placeholderText":"Search for friends"},
{
          "id":"86c829d8c3ec478ca40643b262576099",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":420},
            "size":{
              "width":300,
              "height":50}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open location in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"location.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"4aa29a849eea4393b66a6b3edaf47166",
          "label":"3",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":false,
          "style":{
            "location":{
              "x":260,
              "y":195},
            "size":{
              "width":30,
              "height":30},
            "visible":false},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ff9170b2c45e4f298d40b2b503bae6ef",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "location":{
                  "x":260,
                  "y":195},
                "size":{
                  "width":30,
                  "height":30},
                "visible":false},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/likes/chinesebtn_u2.png"}},
{
          "id":"ba55c4b32a0e4e93b4dc0888f463582c",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "size":{
              "width":60,
              "height":50}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Back in Current Window",
                      "target":{
                        "targetType":"backUrl",
                        "includeVariables":false},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"38cc812fa8d344b68f6da910b1c18f9e",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":272,
              "y":7},
            "size":{
              "width":35,
              "height":35}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"89f067a959714d7bbacd6661dfc7b9f8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":272,
                  "y":7},
                "size":{
                  "width":35,
                  "height":35}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/create_new_event/u5.png"}},
{
          "id":"dc1e343c458e4e438bcf12c5e3467a45",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":272,
              "y":10},
            "size":{
              "width":38,
              "height":32}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Homepage-confirmed in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"homepage-confirmed.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true}]}},
  "masters":{
},
  "objectPaths":{
    "318f6baa86684cb1a952574e287b4180":{
      "scriptId":"u0"},
    "66427b11df70457d9e431252aba996b4":{
      "scriptId":"u1"},
    "5f70edcf4312438c810f13d0b8a14b50":{
      "scriptId":"u2"},
    "8636e255f35f4952a993d58e33dc44d6":{
      "scriptId":"u3"},
    "09e4d65f908143f8954258f6f454b0d3":{
      "scriptId":"u4"},
    "4ea18625801f43579ec38bb7c1135c10":{
      "scriptId":"u5"},
    "e81548a619f84132be1a56ed97e614a8":{
      "scriptId":"u6"},
    "38c16340c4824d2783ab741009c75b98":{
      "scriptId":"u7"},
    "6634a6c14bdf476daca59c2a3025356b":{
      "scriptId":"u8"},
    "6fc5a7a401fd4372a0aa20a0a70148f4":{
      "scriptId":"u9"},
    "3e9740f7b6064e0482fc9e95891ca6e0":{
      "scriptId":"u10"},
    "5732f510076a434d93fee9a6f76793e2":{
      "scriptId":"u11"},
    "763386a6a7094fb1b7e701e2d926c5ea":{
      "scriptId":"u12"},
    "837b4219f0fa41c1ab10234ac301ebfc":{
      "scriptId":"u13"},
    "73c7f26e05f14a3aa9ae9ee28c2b3871":{
      "scriptId":"u14"},
    "ac952bcd0e20413882c181c3cfd43f76":{
      "scriptId":"u15"},
    "3782ff02c6b84c1bae13fd81f74a1988":{
      "scriptId":"u16"},
    "60cb7a8fbbaf496e8f3c2d99b1e00234":{
      "scriptId":"u17"},
    "86c829d8c3ec478ca40643b262576099":{
      "scriptId":"u18"},
    "4aa29a849eea4393b66a6b3edaf47166":{
      "scriptId":"u19"},
    "ff9170b2c45e4f298d40b2b503bae6ef":{
      "scriptId":"u20"},
    "ba55c4b32a0e4e93b4dc0888f463582c":{
      "scriptId":"u21"},
    "38cc812fa8d344b68f6da910b1c18f9e":{
      "scriptId":"u22"},
    "89f067a959714d7bbacd6661dfc7b9f8":{
      "scriptId":"u23"},
    "dc1e343c458e4e438bcf12c5e3467a45":{
      "scriptId":"u24"}}});