$axure.loadCurrentPage({
  "url":"create_new_event.html",
  "generationDate":new Date(1397114342675.89),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"cd70c5284ff848bb998ecc11575acad1",
    "type":"Axure:Page",
    "name":"Create New Event",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"54f701ce436c4e25a27921abd0c0e333",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":-15},
            "size":{
              "width":320,
              "height":568}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ccc035441a73477e9048ed730ed99228",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":-15},
                "size":{
                  "width":320,
                  "height":568}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/create_new_event/u0.png"}},
{
          "id":"115f104f2e5f45bca1885b56183e92ef",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontName":"'SourceSansPro-Light', 'Source Sans Pro ExtraLight', 'Source Sans Pro'",
            "fontSize":"16px",
            "fontWeight":"200",
            "location":{
              "x":28,
              "y":99},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
},
          "placeholderText":"DATE"},
{
          "id":"99bf2cc046c047b2a5cb7fbd729d588d",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontName":"'SourceSansPro-Light', 'Source Sans Pro ExtraLight', 'Source Sans Pro'",
            "fontSize":"16px",
            "fontWeight":"200",
            "location":{
              "x":28,
              "y":142},
            "size":{
              "width":200,
              "height":40}},
          "adaptiveStyles":{
},
          "placeholderText":"TIME"},
{
          "id":"7e1c737bc84b47018dbd8ef6be978d2b",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":440},
            "size":{
              "width":300,
              "height":50}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Add participant in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"add_participant.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"671f8980d02e43e9bd33f42c96a45072",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":272,
              "y":7},
            "size":{
              "width":35,
              "height":35}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"41943ef6c6244f3bbb35183e63bc257e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":272,
                  "y":7},
                "size":{
                  "width":35,
                  "height":35}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/create_new_event/u5.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "54f701ce436c4e25a27921abd0c0e333":{
      "scriptId":"u0"},
    "ccc035441a73477e9048ed730ed99228":{
      "scriptId":"u1"},
    "115f104f2e5f45bca1885b56183e92ef":{
      "scriptId":"u2"},
    "99bf2cc046c047b2a5cb7fbd729d588d":{
      "scriptId":"u3"},
    "7e1c737bc84b47018dbd8ef6be978d2b":{
      "scriptId":"u4"},
    "671f8980d02e43e9bd33f42c96a45072":{
      "scriptId":"u5"},
    "41943ef6c6244f3bbb35183e63bc257e":{
      "scriptId":"u6"}}});