$axure.loadCurrentPage({
  "url":"create_new_event.html",
  "generationDate":new Date(1397120260639.01),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"cd70c5284ff848bb998ecc11575acad1",
    "type":"Axure:Page",
    "name":"Create New Event",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"54f701ce436c4e25a27921abd0c0e333",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":-15},
            "size":{
              "width":320,
              "height":568}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ccc035441a73477e9048ed730ed99228",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":-15},
                "size":{
                  "width":320,
                  "height":568}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/create_new_event/u0.png"}},
{
          "id":"115f104f2e5f45bca1885b56183e92ef",
          "label":"date",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontName":"'SourceSansPro-Light', 'Source Sans Pro ExtraLight', 'Source Sans Pro'",
            "fontSize":"16px",
            "fontWeight":"200",
            "location":{
              "x":28,
              "y":99},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
},
          "placeholderText":"DATE"},
{
          "id":"99bf2cc046c047b2a5cb7fbd729d588d",
          "label":"time",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontName":"'SourceSansPro-Light', 'Source Sans Pro ExtraLight', 'Source Sans Pro'",
            "fontSize":"16px",
            "fontWeight":"200",
            "location":{
              "x":28,
              "y":142},
            "size":{
              "width":200,
              "height":40}},
          "adaptiveStyles":{
},
          "placeholderText":"TIME"},
{
          "id":"7e1c737bc84b47018dbd8ef6be978d2b",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":440},
            "size":{
              "width":300,
              "height":50}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1<br> (If text on date equals &quot;&quot;)",
                  "isNewIfGroup":false,
                  "condition":{
                    "exprType":"binaryOp",
                    "op":"==",
                    "leftExpr":{
                      "exprType":"fcall",
                      "functionName":"GetWidgetText",
                      "arguments":[{
                          "exprType":"pathLiteral",
                          "isThis":false,
                          "isFocused":false,
                          "isTarget":false,
                          "value":["115f104f2e5f45bca1885b56183e92ef"]}]},
                    "rightExpr":{
                      "exprType":"stringLiteral",
                      "value":"",
                      "stos":[]}},
                  "actions":[{
                      "action":"setPanelState",
                      "description":"Set errorMsg to blank",
                      "panelsToStates":[{
                          "panelPath":["805047b8a5924bfc97e36a66e8129ff7"],
                          "stateInfo":{
                            "setStateType":"diagram",
                            "stateNumber":2,
                            "stateValue":{
                              "exprType":"stringLiteral",
                              "value":"1",
                              "stos":[]},
                            "loop":false,
                            "showWhenSet":false,
                            "options":{
                              "compress":false}}}]}]},
{
                  "description":"Case 2<br> (Else If text on time equals &quot;&quot;)",
                  "isNewIfGroup":false,
                  "condition":{
                    "exprType":"binaryOp",
                    "op":"==",
                    "leftExpr":{
                      "exprType":"fcall",
                      "functionName":"GetWidgetText",
                      "arguments":[{
                          "exprType":"pathLiteral",
                          "isThis":false,
                          "isFocused":false,
                          "isTarget":false,
                          "value":["99bf2cc046c047b2a5cb7fbd729d588d"]}]},
                    "rightExpr":{
                      "exprType":"stringLiteral",
                      "value":"",
                      "stos":[]}},
                  "actions":[{
                      "action":"setPanelState",
                      "description":"Set errorMsg to blank",
                      "panelsToStates":[{
                          "panelPath":["805047b8a5924bfc97e36a66e8129ff7"],
                          "stateInfo":{
                            "setStateType":"diagram",
                            "stateNumber":2,
                            "stateValue":{
                              "exprType":"stringLiteral",
                              "value":"1",
                              "stos":[]},
                            "loop":false,
                            "showWhenSet":false,
                            "options":{
                              "compress":false}}}]}]},
{
                  "description":"Case 3<br> (Else If True)",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Add participant in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"add_participant.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"671f8980d02e43e9bd33f42c96a45072",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":272,
              "y":7},
            "size":{
              "width":35,
              "height":35}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"41943ef6c6244f3bbb35183e63bc257e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":272,
                  "y":7},
                "size":{
                  "width":35,
                  "height":35}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/create_new_event/u5.png"}},
{
          "id":"805047b8a5924bfc97e36a66e8129ff7",
          "label":"errorMsg",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":210},
            "size":{
              "width":320,
              "height":200}},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"052e1f2787fe4e8b8a5bfbe33dcc2fa8",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}},
{
              "id":"f774c6eaee4f4bb591303d6001fb16b6",
              "label":"blank",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"90d3cdce58264ac3a63c2440b49038eb",
                  "label":"",
                  "parentDynamicPanel":"805047b8a5924bfc97e36a66e8129ff7",
                  "panelIndex":1,
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":320,
                      "height":200}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"228e6205f78f4187813160141ada6531",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"805047b8a5924bfc97e36a66e8129ff7",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":320,
                          "height":200}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/register/u4.png"}},
{
                  "id":"a979c1894a004aad94a005e9f3a1ae6c",
                  "label":"",
                  "parentDynamicPanel":"805047b8a5924bfc97e36a66e8129ff7",
                  "panelIndex":1,
                  "type":"imageMapRegion",
                  "styleType":"imageMapRegion",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":270,
                      "y":47},
                    "size":{
                      "width":40,
                      "height":30}},
                  "adaptiveStyles":{
},
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"setPanelState",
                              "description":"Set errorMsg to State1",
                              "panelsToStates":[{
                                  "panelPath":["805047b8a5924bfc97e36a66e8129ff7"],
                                  "stateInfo":{
                                    "setStateType":"diagram",
                                    "stateNumber":1,
                                    "stateValue":{
                                      "exprType":"stringLiteral",
                                      "value":"1",
                                      "stos":[]},
                                    "loop":false,
                                    "showWhenSet":false,
                                    "options":{
                                      "compress":false}}}]}]}]}},
                  "tabbable":true}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}}]}]}},
  "masters":{
},
  "objectPaths":{
    "54f701ce436c4e25a27921abd0c0e333":{
      "scriptId":"u0"},
    "ccc035441a73477e9048ed730ed99228":{
      "scriptId":"u1"},
    "115f104f2e5f45bca1885b56183e92ef":{
      "scriptId":"u2"},
    "99bf2cc046c047b2a5cb7fbd729d588d":{
      "scriptId":"u3"},
    "7e1c737bc84b47018dbd8ef6be978d2b":{
      "scriptId":"u4"},
    "671f8980d02e43e9bd33f42c96a45072":{
      "scriptId":"u5"},
    "41943ef6c6244f3bbb35183e63bc257e":{
      "scriptId":"u6"},
    "805047b8a5924bfc97e36a66e8129ff7":{
      "scriptId":"u7"},
    "90d3cdce58264ac3a63c2440b49038eb":{
      "scriptId":"u8"},
    "228e6205f78f4187813160141ada6531":{
      "scriptId":"u9"},
    "a979c1894a004aad94a005e9f3a1ae6c":{
      "scriptId":"u10"}}});